build: off

environment:

 matrix:
  - GHC_VER: 8.2.1
  - GHC_VER: 8.0.2
  - GHC_VER: 7.10.3
  - GHC_VER: 7.8.4

matrix:
  fast_finish: true

install:
  - appveyor-retry choco install -y ghc --version %GHC_VER%
  - refreshenv
  - set BUILD_DIR=$HOME/dist
  - cabal --version
  - ghc --version
  - cabal update
  - cabal install cpphs-1.20.8
  - cabal install alex happy
  - cabal install --only-dependencies
  - cabal install
